name: Generate IPTV Playlist

on:
  schedule:
    - cron: '0 * * * *' # প্রতি ঘণ্টায় আপডেট হবে
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Generate Playlist
        run: |
          python3 generate_playlist.py

      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Auto-update IPTV Playlist"
          git push
          
